name: CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Tests
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  docker:
    name: Build & Push Docker
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/yliesn/marketplace:${{ github.sha }}
            ghcr.io/yliesn/marketplace:latest